## Well, to be honest I struggled for a couple of days... finally I realized it was literally writting
## down what they are asking for. Still difficult tho, I find R very messy in comparison to other
## languages.

## So makeCacheMatrix store a generated matrix
makeCacheMatrix <- function(x = matrix()){
        inv <- NULL
        set <- function(y){
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinv <- function(solvemat) inv <<- solvemat
        getinv <- function() inv
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## This one computes the inverse of the matrix generated by "makeCacheMatrix" function
cacheSolve <- function(x, ...){
        inv <- x$getinv()
        if(!is.null(inv)){
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        inv <- solve(data)
        x$setinv(inv)
        inv
}
